name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * 0,2,5" }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN  }}
          # intro
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          # languages
          plugin_languages: yes
          # pagespeed
          # might require more tokens
          # plugin_pagespeed: yes
          # plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          # plugin_pagespeed_detailed: no # Print detailed audit metrics
          # plugin_pagespeed_screenshot: no # Display a screenshot of your website
          # plugin_pagespeed_url: .user.website # Website to audit (defaults to your GitHub linked website)
