name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * 0,2,5" }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}
          # intro
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          # languages
          plugin_languages: yes
          # topics plugins
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
